version: '3.8'

services:
  web:
    build: .
    command: uvicorn core.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8002:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /usr/bin/pg_config:/usr/bin/pg_config
    expose:
      - 5432
    env_file:
      - .env

volumes:
  postgres_data: