"""remove negative image model

Revision ID: 3c90230b0912
Revises: a7781a5455ae
Create Date: 2021-07-30 18:34:41.293473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c90230b0912'
down_revision = 'a7781a5455ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ovision_negative_image_id', table_name='ovision_negative_image')
    op.drop_table('ovision_negative_image')
    op.add_column('ovision_image', sa.Column('negative_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ovision_image', 'negative_image')
    op.create_table('ovision_negative_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('negative_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['ovision_image.id'], name='ovision_negative_image_image_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ovision_negative_image_pkey')
    )
    op.create_index('ix_ovision_negative_image_id', 'ovision_negative_image', ['id'], unique=False)
    # ### end Alembic commands ###
