"""add models

Revision ID: a7781a5455ae
Revises: 
Create Date: 2021-07-30 17:57:03.846223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7781a5455ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ovision_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ovision_image_id'), 'ovision_image', ['id'], unique=True)
    op.create_table('ovision_negative_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('negative_image', sa.String(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['ovision_image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ovision_negative_image_id'), 'ovision_negative_image', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ovision_negative_image_id'), table_name='ovision_negative_image')
    op.drop_table('ovision_negative_image')
    op.drop_index(op.f('ix_ovision_image_id'), table_name='ovision_image')
    op.drop_table('ovision_image')
    # ### end Alembic commands ###
